packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

autoInstallPeers: true
strictPeerDependencies: true
linkWorkspacePackages: true
saveWorkspaceProtocol: rolling
sharedWorkspaceLockfile: true

allowBuilds:
  esbuild: true
  "@gorules/zen-engine": true
  sharp: true
  unrs-resolver: true
